Feature/db relations(pk/fk)
RawMajkel/MyPiggyBank pull request #16
Opened 2020-04-27 12:53 UTC by bartlomiej96

Entities associations.
DbSet objects added to Context.
Attribute name changes with primary key annotation for Email in User.

2020-04-27 15:49 UTC, kacper-matuszek requested changes

2020-04-27 15:49 UTC, Kacper096 commented on MyPiggyBank.Data/Model/User.cs
>          public string Email { get; set; }
Trzeba ustawić, aby był "required". Nie możemy mieć użytkownika w bazie, który będzie przyjmował null

2020-04-27 15:49 UTC, Kacper096 commented on MyPiggyBank.Data/Model/User.cs
>          public string PasswordHash { get; set; }
To samo co przy "UserName"

2020-04-27 15:49 UTC, Kacper096 commented on MyPiggyBank.Data/Model/Resource.cs
>          public string Currency { get; set; }
Jeśli "Value" nie może być nullem to currency też. Zmiana na required. Nawet jeśli będzie wartość 0 to i tak musimy mieć jakąś walutę.

2020-04-27 15:49 UTC, Kacper096 commented on MyPiggyBank.Data/Model/Resource.cs
> +        public Guid UserId { get; set; }
Resource powinien też zawsze mieć nazwę jak go tworzymy. Nawet jakąś domyślną. Nie możemy mieć "resource" bez nazwy.

2020-04-27 15:49 UTC, Kacper096 commented on MyPiggyBank.Data/Model/Resource.cs
>          public string Name { get; set; }
Jako required. Nie możemy miec nulla na bazie.

2020-04-27 15:49 UTC, Kacper096 commented on MyPiggyBank.Data/Model/OperationCategory.cs
> +        public Guid UserId { get; set; }
Trzymajmy się jednej konwencji. Jeśli w innych klasach na przykład "Operation". 
`       public virtual Resource Resource { get; set; }
        public virtual OperationCategory OperationCategory { get; set; }`
Nie dodawaliśmy `public Guid ResourceId {get;set;}` to tutaj też nie dodajemy czegoś takiego. 
Chyba, że dodajemy w klasie "Operation"
`public Guid ResourceId {get;set;}
 public Guid OperationCategory {get;set;}`.
Tak samo w innych klasach. Ja proponuje cos takiego dodać do tamtych klas, bo na przykład "ktoś" robiąc linq to sql będzie mógł w łatwy sposób łączyć tabele. Inna sytuacja jest jeśli używamy linq to sql fluent.

2020-04-27 15:49 UTC, Kacper096 commented on MyPiggyBank.Data/Model/CyclicOperation.cs
>          public string Period { get; set; }
Zmiana typu period na int. W klasie biznesowej bedzie on enumem. String jest niebezpieczny, bo będziemy mogli do niego cokolwiek dać. Tak będzie to bardziej rygorystyczne.

2020-04-27 15:49 UTC, Kacper096 commented on MyPiggyBank.Data/Model/Resource.cs
>          public string Name { get; set; }
Nazwa Resource tez raczej nie moze byc nullem

2020-04-27 15:49 UTC, Kacper096 commented on MyPiggyBank.Data/Model/CyclicOperation.cs
>          public string Period { get; set; }
Zmiana typu ze string na int. W klasie biznesowej będzie on Enumem. W ten sposób bedzie to bardziej rygorystyczne. Nie pojawi się opcja, że cokolwiek się tam "dostanie".

2020-04-27 15:54 UTC, Kacper096 commented on MyPiggyBank.Data/Model/Operation.cs
>          public decimal Value { get; set; }
Operacja też powinna posiadać walutę, jeśli mamy tutaj jakąś wartość.

2020-04-27 20:59 UTC, kacper-matuszek approved these changes

2020-04-27 23:48 UTC, Sinity approved these changes

2020-04-28 21:17 UTC, kacper-matuszek approved these changes

2020-05-07 19:55 UTC, merged